name: CD
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ./app
            git pull
            cd ./backend
            npm install
            npm run build
            npm run start
            cd ../frontend
            npm run build
            node .output/server/index.mjs
            exit
