name: CD
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
<<<<<<< HEAD
            cd ./app
            git pull
            cd ./backend
            npm install
=======
            git pull
>>>>>>> 1c132d0c4187a39cc76d9fa1dc8b706d42da1568
