name: CD
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            pm2 stop backend
            pm2 stop frontend
            cd ~/app
            git@github.com:pantelav/barbershop.git
            git branch -m master main
            git pull origin main
            cd ./backend
            npm install
            npm run build
            cd ../frontend
            npm install
            npm run build
            pm2 start backend
            pm2 start frontend
            exit
